### ISSUE TITLE
子目录名称长度问题

### ISSUE THREAD

**Issue by NKcell** [honjun/hexo-theme-sakura#10]
清单目录下的子目录名称稍长就回换行，比如这里的py高级变为了两行
<img width="201" alt="屏幕快照 2019-03-16 下午12 57 12" src="https://user-images.githubusercontent.com/43327682/54470917-604c2380-47eb-11e9-85dd-a4a8067d79f8.png">

**Comment by honjun** [comment]
这个需要你自己改下css宽度，毕竟不是每个人的目录都是四个字的，只有两个字设成4个字又太宽。还有钻石小姐姐很漂亮

**Comment by NKcell** [comment]
> 这个需要你自己改下css宽度，毕竟不是每个人的目录都是四个字的，只有两个字设成4个字又太宽。还有钻石小姐姐很漂亮

嗯嗯，谢谢大佬
