### ISSUE TITLE
PHP环境

### ISSUE THREAD

**Issue by LeYiAoCC** [honjun/hexo-theme-sakura#13]
这个也跟Sakura一样只支持PHP7.1和7.2环境嘛

**Comment by mashirozx** [comment]
这个是[hexo](https://hexo.io/zh-cn/index.html)主题，依赖node.js而非php

**Comment by AngelKitty** [comment]
> 这个是[hexo](https://hexo.io/zh-cn/index.html)主题，依赖node.js而非php

但是如果想要搭建live2d API，这个有办法配置PHP环境嘛，我尝试了很多次，都没有办法搭建成功
