### ISSUE TITLE
如何去除公告

### ISSUE THREAD

**Issue by troyliu0105** [honjun/hexo-theme-sakura#15]
如果只是简单地移除`notice`字段，还是会显示公告框，如何完全消除呢？
![image](https://user-images.githubusercontent.com/5518286/58404540-ef9d6f00-8097-11e9-9c4f-73669d6e1136.png)

**Comment by honjun** [comment]
删除themes\Sakura\layout\index.ejs中的<div class="notice" style="margin-top:60px">
    <i class="iconfont icon-notification">
    </i>
    <div class="notice-content"><%= theme.notice%></div>
  </div>，或者更新主题
