### ISSUE TITLE
报告一个小bug

### ISSUE THREAD

**Issue by SpringYeh** [honjun/hexo-theme-sakura#17]
友人帐（links）和赞赏（donate）俩页面下面的用户信息改了之后还是显示博主原信息（hojun），暂时我是用 <%- theme.siteName %> 直接代替文本hojun，因为sitename和作者名一样

**Comment by honjun** [comment]
配置没改，作者信息是在根目录config

**Comment by SpringYeh** [comment]
> 配置没改，作者信息是在根目录config

最近几天又捣鼓了一阵，已经搞清楚了！ ^_^
