### ISSUE TITLE
鼠标的颜色可以改变吗, 因为当我把鼠标移到代码区时, 会与代码颜色混淆

### ISSUE THREAD

**Issue by BlameKidd** [honjun/hexo-theme-sakura#23]
不知道怎么把鼠标截下来..............看标题应该可以懂吧

**Comment by LittleChai** [comment]
这个鼠标样式就是图片，如果你想更换的话可以去 主题下的source>css>style.css文件下搜索cursor,
然后把对应的鼠标样式的url地址替换掉
