### ISSUE TITLE
页面排版混乱问题

### ISSUE THREAD

**Issue by eccx400** [honjun/hexo-theme-sakura#25]
hexo安装以后页面排版混乱怎么解决？

安装过程 (在 VS code 的 terminal 上跑):
在git上下载主题
npm install
编辑_config.yml 的 deploy git 和 URL 部分
npm install hexo-deployer-git --save
hexo clean
hexo g
hexo d

deploy 完后打开问题如图，求解 （hexo server 试过好像也有这个问题）

![捕获](https://user-images.githubusercontent.com/41842161/60934516-1d154380-a2f9-11e9-9a9f-7b06d09fa119.PNG)

![捕获2](https://user-images.githubusercontent.com/41842161/60934565-4df57880-a2f9-11e9-8e29-4ebc1521bd73.PNG)

PS：前面装过几次有一两次没有出现问题，不知为什么

**Comment by eccx400** [comment]
I fixed it wwww

**Comment by vearvip** [comment]
你好，请问是怎么解决的呢，我也碰到了这个问题

**Comment by eccx400** [comment]
因为我用的是 GitHub Pages, 所以把 Repo 命名为 [用户名].github.io 好像就可以了
