### ISSUE TITLE
Pjax 修复

### ISSUE THREAD

**Issue by mashirozx** [honjun/hexo-theme-sakura#3]
[Pjax](https://github.com/defunkt/jquery-pjax) 实现的页面无刷新加载。

原理是获取即将加载的页面，抠取 pjax 容器中间的部分替换原有网页 pjax 容器中间部分：
```html
<header>balabala</header>
<body id="pjax-container">原网页内容</body>
<footer>balabala</footer>
```
经过 pjax 处理后
```html
<header>balabala</header>
<body id="pjax-container">新网页内容</body>
<footer>balabala</footer>
```
在 Sakura 中，设置的 pjax 容器是 `#page`，所以应该把页面正文部分放进 `#page` 中。所以在你这边的改法应该是把 `<div id="content">`中的内容放进 `<div id="page">` 中：

![image](https://user-images.githubusercontent.com/16148054/50844746-60244780-13a6-11e9-9c2a-34d0cbbcfc2e.png)

**Comment by honjun** [comment]
后期修复后期修复23333~

**Comment by honjun** [comment]
已修复
