### ISSUE TITLE
请求主题标头字体适配&代码块问题

### ISSUE THREAD

**Issue by wjy20030407** [honjun/hexo-theme-sakura#5]
![](https://i.loli.net/2019/02/13/5c6307ef4ff0f.png)
![](https://i.loli.net/2019/02/13/5c6307ef4101a.png)
---
![](https://i.loli.net/2019/02/13/5c6308892275f.png)

**Comment by honjun** [comment]
???

**Comment by wjy20030407** [comment]
> ???

问题如图，文字Logo字体与原主题不同`影响美观`
代码块主题我一安装上去不知道为什么就成这样了

**Comment by honjun** [comment]
logo字体是原作者自己设置的logo字体哦（Moe-Mashiro），你自己设计个字体或logo导入即可。代码块的话需要使用规范的md代码块语法才行，因为头部是有语言名内容的。```html```
![image](https://user-images.githubusercontent.com/20104266/52694947-3c0be580-2fa6-11e9-876c-1fc0e5004a4b.png)
