### ISSUE TITLE
请问怎么关闭startdash

### ISSUE THREAD

**Issue by guohoo** [honjun/hexo-theme-sakura#56]
试过在主题目录下的_config里注释掉，或者改成startdash: false都不行

**Comment by aiupc** [comment]
同问，解决了吗？

**Comment by aiupc** [comment]
解决了，把themes/Sakura/layout/index.ejs中的<%- partial('_partial/startdash') %> 注释即可

**Comment by guohoo** [comment]
> 解决了，把themes/Sakura/layout/index.ejs中的<%- partial('_partial/startdash') %> 注释即可

我是在themes/Sakura/layout/_partial/startdash.ejs用`<% if (theme.startdash) { %>`和`<% } %>`把原来的内容括起来
这样就可以在_config中配置`startdash: false`
