### ISSUE TITLE
mathjax与pjax不兼容

### ISSUE THREAD

**Issue by attack204** [honjun/hexo-theme-sakura#6]
如题，开启pjax之后，每次加载完新页面需要手动刷新才能加载mathjax。
开启mathjax的方法参考自[这里](https://blog.csdn.net/u014630987/article/details/78670258)

**Comment by mashirozx** [comment]
在这里添加pjax重载函数：
https://github.com/honjun/hexo-theme-sakura/blob/master/themes/Sakura/source/js/sakura-app.js#L72
