### ISSUE TITLE
waline评论系统按钮显示问题

### ISSUE THREAD

**Issue by naphth** [honjun/hexo-theme-sakura#65]
直接在服务端地址（serverURL）打开是显示正常的：
![sendpix1](https://user-images.githubusercontent.com/86549046/153801765-6181702a-45f2-40cd-be3f-8b8d22a95b8e.jpg)

在博客中，右下角的按钮会迅速缩小至几乎不可见：
![sendpix0](https://user-images.githubusercontent.com/86549046/153802095-b9e529ad-fcec-45fb-88cf-d4204cafaa80.jpg)

手机端也一样：
![714400D2DEE4108B35E0CBFDB6DF3957](https://user-images.githubusercontent.com/86549046/153802166-1aa55924-3f89-49bf-84d7-32e75bef65b8.jpg)

**Comment by naphth** [comment]
改了下css里的font-size，已解决

**Comment by XuanMiaoSama** [comment]
@naphth 我遇到了和您一样的问题，想请问您修改的css文件是哪一个
