### ISSUE TITLE
about界面pjax不兼容以及目录的修正

### ISSUE THREAD

**Issue by AngelKitty** [honjun/hexo-theme-sakura#7]
/about/ 关于我的页面需要手动刷新才能显示，以及文章缺少一个目录，Sakura主题似乎是用tocbot，但好像手动没加成功，特提出此建议

**Comment by mashirozx** [comment]
看起来tocbot的初始函数已经移被除了。
可参考这篇添加
https://2heng.xin/2018/02/13/add-a-toc-for-your-article/
